### ISSUE TITLE
About RTE strategy

### ISSUE THREAD

**Issue by sandman13** [acbull/pyHGT#7]
Hi~  Thanks for the nice job!
I'm confused of the part of RTE strategy. 
(1) Does T(s)  mean a list that contains all timestamps that s occurs? 
(2) Is the length of T(t) and T(s)  always equal? 
(3) How to do T(t)-T(s)? Will this gap be negative?

**Comment by acbull** [comment]
(1) No. It means the timestamp of node s in our sampled graph. If s is the event node (such as a published paper with a specific timestamp), we will directly use its time. Otherwise (such as an author, who will not have a specific timestamp), we will inherently use its source node's timestamp. For example, we sample an author node from a paper, then we'll use the paper's published time as the timestamp for this author, in this sampled graph. Such a procedure can be found in https://github.com/acbull/pyHGT/blob/2f7f735ffd1b1b07d564a5dcbb0ef815a03be484/data.py#L126
(2) T is the timestamp (an integer number), and RTE is the temporal embedding (a d-dimension vector). If you mean temporal encoding, they are all d-length.
(3) Just directly calculate the time gap between two nodes. Yes, they can be negative. (This is why in implementation, I added the possible maximum of the time to make sure they are positive so can be indexed, in https://github.com/acbull/pyHGT/blob/2f7f735ffd1b1b07d564a5dcbb0ef815a03be484/data.py#L249)
